name: Tests

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Install Node.js dependencies
              run: npm ci

            - name: Run Vitests
              run: npm run test
